add_newline = true

# [battery]
# full_symbol = "ğŸ”‹"
# charging_symbol = "ğŸ”Œ"
# discharging_symbol = "âš¡"

[directory]
truncation_length = 5
format = "[$path]($style)[$lock_symbol]($lock_style) "

# Replace the "â¯" symbol in the prompt with "âœ"
[character] # The name of the module we are configuring is "character"
success_symbol = "[âœ](bold green)"  # The "success_symbol" segment is being set to "âœ" with the color "bold green"
error_symbol = "[âœ–](bold red) "

[cmd_duration]
min_time = 100
format = " took [$duration]($style)"

[git_branch]
format = " [$symbol$branch]($style) "
symbol = "ğŸŒ± "

# [git_status]
# conflicted = "âš”ï¸ "
# ahead = "ğŸï¸ ğŸ’¨ Ã—${count}"
# behind = "ğŸ¢ Ã—${count}"
# diverged = "ğŸ”± ğŸï¸ ğŸ’¨ Ã—${ahead_count} ğŸ¢ Ã—${behind_count}"
# untracked = "ğŸ›¤ï¸ Ã—${count}"
# stashed = "ğŸ“¦ "
# modified = "ğŸ“ Ã—${count}"
# staged = "ğŸ—ƒï¸ Ã—${count}"
# renamed = "ğŸ“› Ã—${count}"
# deleted = "ğŸ—‘ï¸ Ã—${count}"
# style = "bright-white"
# format = "$all_status$ahead_behind"

# Disable the package module, hiding it from the prompt completely
# [package]
# disabled = true

# [memory_usage]
# format = "$symbol[${ram}( | ${swap})]($style) "
# threshold = 70
# style = "bold dimmed white"
# disabled = false